from tkinter import *
def subst():
    a=int(num1a.get())
    b=int(num2a.get())
    res="result : "+str(a-b)
    result.config(text=res)
sub=Tk()
sub.title("Substraction")
num1=Label(sub,text="Enter Number1:")
num1a=Entry(sub)
num1.grid(row=0,column=0)
num1a.grid(row=0,column=1)
num2=Label(sub,text='Enter Number2:')
num2a=Entry(sub)
num2.grid(row=1,column=0)
num2a.grid(row=1,column=1)
substract=Button(sub,text='Substract',command=subst)
substract.grid(row=2,column=0)
result=Label(sub,text="Result:")
result.grid(row=2,column=1)
sub.mainloop()